package axparameter

/*
#cgo pkg-config: glib-2.0 axparameter
#include <glib.h>
#include <axsdk/ax_parameter/ax_parameter_error.h>
*/
import "C"

// AXParameterErrorCode defines Go equivalents of C enum values.
type AXParameterErrorCode int

const (
	AX_PARAMETER_INVALID_ARG_ERROR AXParameterErrorCode = iota
	AX_PARAMETER_FILE_FD_ERROR
	AX_PARAMETER_FILE_LOCK_ERROR
	AX_PARAMETER_FILE_OPEN_ERROR
	AX_PARAMETER_FILE_FORMAT_ERROR
	AX_PARAMETER_FILE_CREATE_ERROR
	AX_PARAMETER_FILE_WRITE_ERROR
	AX_PARAMETER_FILE_LINK_ERROR
	AX_PARAMETER_PARAM_LIST_ERROR
	AX_PARAMETER_PARAM_GET_ERROR
	AX_PARAMETER_PARAM_PATH_ERROR
	AX_PARAMETER_PARAM_SYNC_ERROR
	AX_PARAMETER_PARAM_EXIST_ERROR
	AX_PARAMETER_PARAM_ADDED_ERROR
	AX_PARAMETER_PARAM_READ_GROUP_ERROR
	AX_PARAMETER_PARAM_SET_ERROR
	AX_PARAMETER_DBUS_SETUP_ERROR
	AX_PARAMETER_FILE_UNLINK_ERROR
	AX_PARAMETER_FILE_PATH_ERROR
	AX_PARAMETER_FILE_SYNC_ERROR
	AX_PARAMETER_FILE_RENAME_ERROR
)

// String provides a string representation for AXParameterErrorCode.
func (e AXParameterErrorCode) String() string {
	switch e {
	case AX_PARAMETER_INVALID_ARG_ERROR:
		return "AX_PARAMETER_INVALID_ARG_ERROR"
	case AX_PARAMETER_FILE_FD_ERROR:
		return "AX_PARAMETER_FILE_FD_ERROR"
	case AX_PARAMETER_FILE_LOCK_ERROR:
		return "AX_PARAMETER_FILE_LOCK_ERROR"
	case AX_PARAMETER_FILE_OPEN_ERROR:
		return "AX_PARAMETER_FILE_OPEN_ERROR"
	case AX_PARAMETER_FILE_FORMAT_ERROR:
		return "AX_PARAMETER_FILE_FORMAT_ERROR"
	case AX_PARAMETER_FILE_CREATE_ERROR:
		return "AX_PARAMETER_FILE_CREATE_ERROR"
	case AX_PARAMETER_FILE_WRITE_ERROR:
		return "AX_PARAMETER_FILE_WRITE_ERROR"
	case AX_PARAMETER_FILE_LINK_ERROR:
		return "AX_PARAMETER_FILE_LINK_ERROR"
	case AX_PARAMETER_PARAM_LIST_ERROR:
		return "AX_PARAMETER_PARAM_LIST_ERROR"
	case AX_PARAMETER_PARAM_GET_ERROR:
		return "AX_PARAMETER_PARAM_GET_ERROR"
	case AX_PARAMETER_PARAM_PATH_ERROR:
		return "AX_PARAMETER_PARAM_PATH_ERROR"
	case AX_PARAMETER_PARAM_SYNC_ERROR:
		return "AX_PARAMETER_PARAM_SYNC_ERROR"
	case AX_PARAMETER_PARAM_EXIST_ERROR:
		return "AX_PARAMETER_PARAM_EXIST_ERROR"
	case AX_PARAMETER_PARAM_ADDED_ERROR:
		return "AX_PARAMETER_PARAM_ADDED_ERROR"
	case AX_PARAMETER_PARAM_READ_GROUP_ERROR:
		return "AX_PARAMETER_PARAM_READ_GROUP_ERROR"
	case AX_PARAMETER_PARAM_SET_ERROR:
		return "AX_PARAMETER_PARAM_SET_ERROR"
	case AX_PARAMETER_DBUS_SETUP_ERROR:
		return "AX_PARAMETER_DBUS_SETUP_ERROR"
	case AX_PARAMETER_FILE_UNLINK_ERROR:
		return "AX_PARAMETER_FILE_UNLINK_ERROR"
	case AX_PARAMETER_FILE_PATH_ERROR:
		return "AX_PARAMETER_FILE_PATH_ERROR"
	case AX_PARAMETER_FILE_SYNC_ERROR:
		return "AX_PARAMETER_FILE_SYNC_ERROR"
	case AX_PARAMETER_FILE_RENAME_ERROR:
		return "AX_PARAMETER_FILE_RENAME_ERROR"
	default:
		return "Unknown AXParameterErrorCode"
	}
}
